package controle_de_consumo_de_agua;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Pedro
 */
public class MundoEducacao extends javax.swing.JFrame {

    Usuario p1 = new Usuario();
    /**
     * Creates new form MundoEducacao
     */
    public MundoEducacao() {
        initComponents();
    }
    
    public MundoEducacao(int id, String nome, String senha, int idade, String sexo, double peso, boolean amamentando, boolean gestante, int dian, int mesn, int anon, int quantidade){
        initComponents();
        lblUsuario.setText("Usuário: " + nome);
        lblTotal.setText("Total: "+quantidade+" ml");
        DefaultTableModel model = (DefaultTableModel)tblUsuario.getModel();
        model.addRow(new Object[]{
            id,
            String.valueOf(nome),
            String.valueOf(senha),
            idade,
            String.valueOf(sexo),
            peso,
            amamentando,
            gestante,
            dian,
            mesn,
            anon,
            quantidade
        });
        p1.setQuantidade(quantidade);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelImagemFundo1 = new controle_de_consumo_de_agua.PainelImagemFundo();
        lblControleConsumoAgua = new javax.swing.JLabel();
        lblMetodo = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblDoisPontos = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtHoras = new javax.swing.JTextField();
        txtMinutos = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngestao = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();
        painelImagemFundo2 = new controle_de_consumo_de_agua.PainelImagemFundo();
        lblControleConsumoAgua2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        lblMetodo2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnExecutar = new javax.swing.JButton();
        btnVoltar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaResultado = new javax.swing.JTextArea();
        lblImage2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/controle_de_consumo_de_agua/CCADrop.png"))); // NOI18N
        jInternalFrame1.setVisible(true);

        painelImagemFundo1.setBackground(new java.awt.Color(51, 51, 51));
        painelImagemFundo1.setImg(new ImageIcon("src/controle_de_consumo_de_agua/CCAWater.jpg"));
        painelImagemFundo1.setLayout(null);

        lblControleConsumoAgua.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblControleConsumoAgua.setText("Controle de Consumo de Água");
        painelImagemFundo1.add(lblControleConsumoAgua);
        lblControleConsumoAgua.setBounds(84, 37, 485, 44);

        lblMetodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMetodo.setText("Método: Mundo Educação");
        painelImagemFundo1.add(lblMetodo);
        lblMetodo.setBounds(258, 99, 161, 17);

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setText("Total: 0 ml");
        painelImagemFundo1.add(lblTotal);
        lblTotal.setBounds(10, 210, 130, 22);

        lblQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuantidade.setText("Quantidade(em ml):");
        painelImagemFundo1.add(lblQuantidade);
        lblQuantidade.setBounds(157, 176, 122, 17);

        lblHorario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHorario.setText("Horário:");
        painelImagemFundo1.add(lblHorario);
        lblHorario.setBounds(481, 176, 49, 17);

        lblDoisPontos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDoisPontos.setText(":");
        painelImagemFundo1.add(lblDoisPontos);
        lblDoisPontos.setBounds(526, 214, 6, 22);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        painelImagemFundo1.add(btnVoltar);
        btnVoltar.setBounds(490, 267, 95, 37);

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        painelImagemFundo1.add(btnAdicionar);
        btnAdicionar.setBounds(251, 267, 129, 37);

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        painelImagemFundo1.add(btnExcluir);
        btnExcluir.setBounds(76, 267, 101, 37);

        txtHoras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        painelImagemFundo1.add(txtHoras);
        txtHoras.setBounds(481, 211, 41, 28);

        txtMinutos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        painelImagemFundo1.add(txtMinutos);
        txtMinutos.setBounds(536, 211, 43, 28);

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        painelImagemFundo1.add(txtQuantidade);
        txtQuantidade.setBounds(157, 211, 97, 28);

        tblIngestao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantidade(ml)", "Horário"
            }
        ));
        jScrollPane1.setViewportView(tblIngestao);

        painelImagemFundo1.add(jScrollPane1);
        jScrollPane1.setBounds(23, 322, 618, 204);

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Senha", "Idade", "Sexo", "Peso", "Amamentando", "Gestante", "DiaNascimento", "MesNascimento", "AnoNascimento", "QuantidadeDiaria"
            }
        ));
        jScrollPane3.setViewportView(tblUsuario);

        painelImagemFundo1.add(jScrollPane3);
        jScrollPane3.setBounds(36, 557, 588, 1);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle_de_consumo_de_agua/CCAWater.jpg"))); // NOI18N
        painelImagemFundo1.add(lblImage);
        lblImage.setBounds(0, 0, 670, 580);

        jTabbedPane1.addTab("Quantidade", painelImagemFundo1);

        painelImagemFundo2.setBackground(new java.awt.Color(51, 51, 51));
        painelImagemFundo2.setImg(new ImageIcon("src/controle_de_consumo_de_agua/CCAWater.jpg"));
        painelImagemFundo2.setLayout(null);

        lblControleConsumoAgua2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblControleConsumoAgua2.setText("Controle de Consumo de Água");
        painelImagemFundo2.add(lblControleConsumoAgua2);
        lblControleConsumoAgua2.setBounds(88, 23, 485, 44);

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalvar.setText("Salvar dados");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        painelImagemFundo2.add(btnSalvar);
        btnSalvar.setBounds(52, 227, 133, 31);

        lblMetodo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMetodo2.setText("Método: Mundo Educação");
        painelImagemFundo2.add(lblMetodo2);
        lblMetodo2.setBounds(251, 73, 161, 17);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUsuario.setText("Usuário:");
        painelImagemFundo2.add(lblUsuario);
        lblUsuario.setBounds(304, 134, 200, 29);

        btnExecutar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExecutar.setText("Executar");
        btnExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecutarActionPerformed(evt);
            }
        });
        painelImagemFundo2.add(btnExecutar);
        btnExecutar.setBounds(304, 227, 99, 31);

        btnVoltar2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar2.setText("Voltar");
        btnVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar2ActionPerformed(evt);
            }
        });
        painelImagemFundo2.add(btnVoltar2);
        btnVoltar2.setBounds(517, 227, 79, 31);

        txaResultado.setColumns(20);
        txaResultado.setRows(5);
        jScrollPane2.setViewportView(txaResultado);

        painelImagemFundo2.add(jScrollPane2);
        jScrollPane2.setBounds(23, 275, 622, 248);

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle_de_consumo_de_agua/CCAWater.jpg"))); // NOI18N
        painelImagemFundo2.add(lblImage2);
        lblImage2.setBounds(0, 0, 670, 580);

        jTabbedPane1.addTab("Resultado", painelImagemFundo2);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        int id = Integer.parseInt(tblUsuario.getValueAt(0, 0).toString());
        String nome = tblUsuario.getValueAt(0, 1).toString();
        String senha = tblUsuario.getValueAt(0, 2).toString();
        int idade = Integer.parseInt(tblUsuario.getValueAt(0, 3).toString());
        String sexo = tblUsuario.getValueAt(0, 4).toString();
        double peso = Double.parseDouble(tblUsuario.getValueAt(0, 5).toString());
        boolean amamentando = Boolean.parseBoolean(tblUsuario.getValueAt(0, 6).toString());
        boolean gestante = Boolean.parseBoolean(tblUsuario.getValueAt(0, 7).toString());
        int dian = Integer.parseInt(tblUsuario.getValueAt(0, 8).toString());
        int mesn = Integer.parseInt(tblUsuario.getValueAt(0, 9).toString());
        int anon = Integer.parseInt(tblUsuario.getValueAt(0, 10).toString());
        int quantidade = Integer.parseInt(tblUsuario.getValueAt(0, 11).toString());
        
        new SelecionarMetodo(id, nome, senha, idade, sexo, peso, amamentando, gestante, dian, mesn, anon, p1.getQuantidade()).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar2ActionPerformed
        int id = Integer.parseInt(tblUsuario.getValueAt(0, 0).toString());
        String nome = tblUsuario.getValueAt(0, 1).toString();
        String senha = tblUsuario.getValueAt(0, 2).toString();
        int idade = Integer.parseInt(tblUsuario.getValueAt(0, 3).toString());
        String sexo = tblUsuario.getValueAt(0, 4).toString();
        double peso = Double.parseDouble(tblUsuario.getValueAt(0, 5).toString());
        boolean amamentando = Boolean.parseBoolean(tblUsuario.getValueAt(0, 6).toString());
        boolean gestante = Boolean.parseBoolean(tblUsuario.getValueAt(0, 7).toString());
        int dian = Integer.parseInt(tblUsuario.getValueAt(0, 8).toString());
        int mesn = Integer.parseInt(tblUsuario.getValueAt(0, 9).toString());
        int anon = Integer.parseInt(tblUsuario.getValueAt(0, 10).toString());
        int quantidade = Integer.parseInt(tblUsuario.getValueAt(0, 11).toString());
        
        new SelecionarMetodo(id, nome, senha, idade, sexo, peso, amamentando, gestante, dian, mesn, anon, p1.getQuantidade()).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltar2ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try{
            int value = Integer.parseInt(tblIngestao.getValueAt(tblIngestao.getSelectedRow(), 1).toString());
            p1.setQuantidade(p1.getQuantidade() - value);
            lblTotal.setText("Total: " + p1.getQuantidade() + " ml");
            ((DefaultTableModel) tblIngestao.getModel()).removeRow(tblIngestao.getSelectedRow());}
        catch(Exception z){
            JOptionPane.showMessageDialog(this, "Selecione a linha a ser apagada!");}
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try{
            int hora = Integer.parseInt(txtHoras.getText());
            int minuto = Integer.parseInt(txtMinutos.getText());
            if (txtQuantidade.getText().equals ("") ||
                txtHoras.getText().equals("") ||
                txtMinutos.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Todos os campos precisam ser preenchidos!");
                return;}
            if(hora >= 24 || minuto >= 60){
                JOptionPane.showMessageDialog(this, "Dados inválidos!");
                return;}
            else{
                DefaultTableModel model = (DefaultTableModel)tblIngestao.getModel();
                String Horario = (hora + " : " + minuto);
                model.addRow(new Object[]{
                    String.valueOf(Horario),
                    Integer.valueOf(txtQuantidade.getText())
                });
                p1.setQuantidade(p1.getQuantidade() + Integer.valueOf(txtQuantidade.getText()));
                lblTotal.setText("Total: " + p1.getQuantidade() + " ml");
                p1.setVezes(p1.getVezes() + 1);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Dados inválidos!");}
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarActionPerformed
        int id = Integer.parseInt(tblUsuario.getValueAt(0, 0).toString());
        String nome = tblUsuario.getValueAt(0, 1).toString();
        String senha = tblUsuario.getValueAt(0, 2).toString();
        int idade = Integer.parseInt(tblUsuario.getValueAt(0, 3).toString());
        String sexo = tblUsuario.getValueAt(0, 4).toString();
        double peso = Double.parseDouble(tblUsuario.getValueAt(0, 5).toString());
        boolean amamentando = Boolean.parseBoolean(tblUsuario.getValueAt(0, 6).toString());
        boolean gestante = Boolean.parseBoolean(tblUsuario.getValueAt(0, 7).toString());
        int dian = Integer.parseInt(tblUsuario.getValueAt(0, 8).toString());
        int mesn = Integer.parseInt(tblUsuario.getValueAt(0, 9).toString());
        int anon = Integer.parseInt(tblUsuario.getValueAt(0, 10).toString());
        
        p1.setSexo(sexo);
        p1.setPeso(peso);
        p1.setNome(nome);
        p1.setMesn(mesn);
        p1.setAnon(anon);
        p1.setDian(dian);
        
        if(p1.Idade() >= 210){
            if(p1.CalculoMundoEduacacao() == p1.getQuantidade()){
                txaResultado.setText(p1.PadraoAdultoMundoEducacao() + p1.AvisoMetaDiariaAtingida() + p1.DicasMundoEducacao() + p1.FontesMetaDiariaAtingidaMundoEducacao());
            }
            if(p1.CalculoMundoEduacacao() > p1.getQuantidade()){
                txaResultado.setText(p1.PadraoAdultoMundoEducacao() + p1.AvisoPoucaAgua() + p1.PoucaAgua() + p1.DicasMundoEducacao() + p1.FontesPoucaAguaMundoEducacao());
            }
            if(p1.CalculoMundoEduacacao() < p1.getQuantidade()){
                txaResultado.setText(p1.PadraoAdultoMundoEducacao() + p1.AvisoMuitaAgua() + p1.MuitaAgua() + p1.DicasMundoEducacao() + p1.FontesMuitaAguaMundoEducacao());
            }
        }
        if (p1.Idade() < 210){
            if(0 == p1.getQuantidade()){
                txaResultado.setText(p1.PadraoBebeMundoEducacao() + p1.AvisoMetaDiariaAtingida() + p1.DeRecemNascidoA6Meses() + p1.DicasMundoEducacao() + p1.FontesMetaDiariaAtingidaMundoEducacao());
            }
            if(p1.getQuantidade() > 0){
                txaResultado.setText(p1.PadraoBebeMundoEducacao() + p1.AvisoMuitaAgua() + p1.DeRecemNascidoA6Meses() + p1.MuitaAgua() + p1.DicasMundoEducacao() + p1.FontesMuitaAguaMundoEducacao());
            }
        }
    }//GEN-LAST:event_btnExecutarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    try{
        int id = Integer.parseInt(tblUsuario.getValueAt(0, 0).toString());
        String nome = tblUsuario.getValueAt(0, 1).toString();
        String senha = tblUsuario.getValueAt(0, 2).toString();
        int idade = Integer.parseInt(tblUsuario.getValueAt(0, 3).toString());
        String sexo = tblUsuario.getValueAt(0, 4).toString();
        double peso = Double.parseDouble(tblUsuario.getValueAt(0, 5).toString());
        boolean amamentando = Boolean.parseBoolean(tblUsuario.getValueAt(0, 6).toString());
        boolean gestante = Boolean.parseBoolean(tblUsuario.getValueAt(0, 7).toString());
        int dian = Integer.parseInt(tblUsuario.getValueAt(0, 8).toString());
        int mesn = Integer.parseInt(tblUsuario.getValueAt(0, 9).toString());
        int anon = Integer.parseInt(tblUsuario.getValueAt(0, 10).toString());
        
        p1.setId(id);
        p1.setGestante(gestante);
        p1.setAmamentando(amamentando);
        p1.setSexo(sexo);
        p1.setAnon(anon);
        p1.setMesn(mesn);
        p1.setDian(dian);
        
        Class.forName("com.mysql.jdbc.Driver");
            
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cca", "root", "");
        
        Statement stmt = con.createStatement();
        
        p1.Idade();
        int bebe = p1.Bebe();
        
            //Recem-nascido a 6 meses.
                if(idade < 1 && bebe <= 6  && p1.isAmamentando() == false && p1.isGestante() == false){
                    p1.setMetacl("0 ml");}

                //De 7 meses a 1 ano.
                if(idade < 1 && bebe > 6  && p1.isAmamentando() == false && p1.isGestante() == false){
                    p1.setMetacl("De 800 ml à 1000 ml");}

                    //De 1 a 3 anos
                    if (idade >= 1 && idade <= 3 && p1.isAmamentando() == false && p1.isGestante() == false){
                        p1.setMetacl("1300 ml");}

                    //De 4 a 8 anos
                    if(idade > 3 && idade <= 8 && p1.isAmamentando() == false && p1.isGestante() == false){
                        p1.setMetacl("1700 ml");}

                    //De 9 a 13 anos
                    if (idade > 8 && idade <= 13){
                        if(p1.getSexo().equals("Masculino")){
                            p1.setMetacl("2400 ml");}
                        if(p1.getSexo().equals("Feminino") && p1.isAmamentando() == false && p1.isGestante() == false){
                            p1.setMetacl("2100 ml");}
                    }

                    //De 14 a 18 anos
                    if(idade > 13 && idade <= 18){
                        if(p1.getSexo().equals("Masculino")){
                            p1.setMetacl("3300 ml");}
                        if(p1.getSexo().equals("Feminino")){
                            if(p1.isGestante() == true){
                                if(p1.isAmamentando() == true){
                                    p1.setMetacl("3700 ml");}
                                if(p1.isAmamentando() == false){
                                    p1.setMetacl("2600 ml");}
                            }
                            if(p1.isGestante() == false){
                                if(p1.isAmamentando() == true){
                                    p1.setMetacl("3400 ml");}
                                if(p1.isAmamentando() == false){
                                    p1.setMetacl("2300 ml");}
                            }
                        }
                    }

                    //Dos 19 anos em diante
                    if(idade > 18){
                        if(p1.getSexo().equals ("Masculino")){
                            p1.setMetacl("3700 ml");}
                        if(p1.getSexo().equals("Feminino")){
                            if(p1.isGestante() == true){
                                if(p1.isAmamentando() == true){
                                    p1.setMetacl("4100 ml");}
                                if(p1.isAmamentando() == false){
                                    p1.setMetacl("3000 ml");}
                            }
                            if(p1.isGestante() == false){
                                if(p1.isAmamentando() == true){
                                    p1.setMetacl("3800 ml");}
                                if(p1.isAmamentando() == false){
                                    p1.setMetacl("2700 ml");}
                            }
                        }
                    }
        p1.setPeso(peso);
        
        p1.setMetame(p1.CalculoMundoEduacacao());
        String metame = p1.getMetame() + " ml";
        
        int dia = p1.getDiaatual();
        int mes = p1.getMesatual();
        int ano = p1.getAnoatual();
        
        String start = "insert into " + nome + "_cca values('"+ nome +"', '0', '0', 'none', 'none', '"+dia+"', '"+mes+"', '"+ano+"');";
        String delete = "delete from " + nome + "_cca where ano = '"+ano+"' and dia = '"+dia+"' and mes = '"+mes+"' limit 2;";
        String add = "insert into " + nome + "_cca values('"+nome+"', '"+p1.getQuantidade()+"', '"+p1.getVezes()+"', '"+p1.getMetacl()+"', '"+metame+"', '"+ dia +"', '"+mes+"', '"+ano+"');";
        
        stmt.executeUpdate(start);
        stmt.executeUpdate(delete);
        stmt.executeUpdate(add);
        JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!");
        con.close();
    }
    catch(Exception a){
        JOptionPane.showMessageDialog(this, "Execute antes de salvar os dados.");
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MundoEducacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MundoEducacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MundoEducacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MundoEducacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MundoEducacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnVoltar2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblControleConsumoAgua;
    private javax.swing.JLabel lblControleConsumoAgua2;
    private javax.swing.JLabel lblDoisPontos;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JLabel lblMetodo2;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUsuario;
    private controle_de_consumo_de_agua.PainelImagemFundo painelImagemFundo1;
    private controle_de_consumo_de_agua.PainelImagemFundo painelImagemFundo2;
    private javax.swing.JTable tblIngestao;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextArea txaResultado;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtMinutos;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
