/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controle_de_consumo_de_agua;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pedro
 */
public class SelecionarMetodo extends javax.swing.JFrame {
    
    Usuario u1 = new Usuario();
    
    public SelecionarMetodo() {
        initComponents();
    }
    
    public SelecionarMetodo(int id, String nome, String senha, int idade, String sexo, double peso, boolean amamentando, boolean gestante, int dian, int mesn, int anon, int quantidade){
        initComponents();
        lblUsuario.setText("Usuário: " + nome);
        DefaultTableModel model = (DefaultTableModel)tblUsuario.getModel();
        model.addRow(new Object[]{
            id,
            String.valueOf(nome),
            String.valueOf(senha),
            idade,
            String.valueOf(sexo),
            peso,
            amamentando,
            gestante,
            dian,
            mesn,
            anon,
            quantidade
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        painelImagemFundo1 = new controle_de_consumo_de_agua.PainelImagemFundo();
        lblSelecionarMetodo = new javax.swing.JLabel();
        lblCCA = new javax.swing.JLabel();
        btnCatracaLivre = new javax.swing.JButton();
        btnMundoEducacao = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        lblInformacaoCL = new javax.swing.JLabel();
        lblInformacaoME = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/controle_de_consumo_de_agua/CCADrop.png"))); // NOI18N
        jInternalFrame1.setVisible(true);

        painelImagemFundo1.setBackground(new java.awt.Color(102, 102, 102));
        painelImagemFundo1.setLayout(null);

        lblSelecionarMetodo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSelecionarMetodo.setText("Selecionar Método");
        painelImagemFundo1.add(lblSelecionarMetodo);
        lblSelecionarMetodo.setBounds(186, 180, 195, 29);

        lblCCA.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblCCA.setText("Controle de Consumo de Água");
        painelImagemFundo1.add(lblCCA);
        lblCCA.setBounds(41, 41, 485, 44);

        btnCatracaLivre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCatracaLivre.setText("Catraca Livre");
        btnCatracaLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatracaLivreActionPerformed(evt);
            }
        });
        painelImagemFundo1.add(btnCatracaLivre);
        btnCatracaLivre.setBounds(41, 252, 173, 37);

        btnMundoEducacao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnMundoEducacao.setText("Mundo Educação");
        btnMundoEducacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMundoEducacaoActionPerformed(evt);
            }
        });
        painelImagemFundo1.add(btnMundoEducacao);
        btnMundoEducacao.setBounds(346, 252, 211, 37);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        painelImagemFundo1.add(btnVoltar);
        btnVoltar.setBounds(236, 461, 95, 37);

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAtualizar.setText("Atualizar informações pessoais");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        painelImagemFundo1.add(btnAtualizar);
        btnAtualizar.setBounds(100, 400, 359, 37);

        btnHistorico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnHistorico.setText("Histórico");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });
        painelImagemFundo1.add(btnHistorico);
        btnHistorico.setBounds(222, 342, 123, 37);

        lblInformacaoCL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInformacaoCL.setText("Base do calculo: Idade");
        painelImagemFundo1.add(lblInformacaoCL);
        lblInformacaoCL.setBounds(41, 295, 136, 17);

        lblInformacaoME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInformacaoME.setText("Base do calculo: Peso");
        painelImagemFundo1.add(lblInformacaoME);
        lblInformacaoME.setBounds(346, 295, 131, 17);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUsuario.setText("Usuário:");
        painelImagemFundo1.add(lblUsuario);
        lblUsuario.setBounds(239, 114, 210, 29);

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Senha", "Idade", "Sexo", "Peso", "Amamentando", "Gestante", "DiaNascimento", "MesNascimento", "AnoNascimento", "QuantidadeDiaria"
            }
        ));
        tblUsuario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblUsuarioPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuario);

        painelImagemFundo1.add(jScrollPane1);
        jScrollPane1.setBounds(57, 504, 452, 1);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle_de_consumo_de_agua/CCAWater.jpg"))); // NOI18N
        painelImagemFundo1.add(lblImage);
        lblImage.setBounds(0, 0, 600, 520);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(painelImagemFundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemFundo1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Login enter = new Login();
        enter.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCatracaLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatracaLivreActionPerformed
    try{
        int id = Integer.parseInt(tblUsuario.getValueAt(0, 0).toString());
        String nome = tblUsuario.getValueAt(0, 1).toString();
        String senha = tblUsuario.getValueAt(0, 2).toString();
        int idade = Integer.parseInt(tblUsuario.getValueAt(0, 3).toString());
        String sexo = tblUsuario.getValueAt(0, 4).toString();
        double peso = Double.parseDouble(tblUsuario.getValueAt(0, 5).toString());
        boolean amamentando = Boolean.parseBoolean(tblUsuario.getValueAt(0, 6).toString());
        boolean gestante = Boolean.parseBoolean(tblUsuario.getValueAt(0, 7).toString());
        int dian = Integer.parseInt(tblUsuario.getValueAt(0, 8).toString());
        int mesn = Integer.parseInt(tblUsuario.getValueAt(0, 9).toString());
        int anon = Integer.parseInt(tblUsuario.getValueAt(0, 10).toString());
        int quantidade = Integer.parseInt(tblUsuario.getValueAt(0, 11).toString());
        
        new CatracaLivre(id, nome, senha, idade, sexo, peso, amamentando, gestante, dian, mesn, anon, quantidade).setVisible(true);
        dispose();}
    catch(Exception a){
        JOptionPane.showMessageDialog(this, "Erro!");
    }
    }//GEN-LAST:event_btnCatracaLivreActionPerformed

    private void btnMundoEducacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMundoEducacaoActionPerformed
    try{
        int id = Integer.parseInt(tblUsuario.getValueAt(0, 0).toString());
        String nome = tblUsuario.getValueAt(0, 1).toString();
        String senha = tblUsuario.getValueAt(0, 2).toString();
        int idade = Integer.parseInt(tblUsuario.getValueAt(0, 3).toString());
        String sexo = tblUsuario.getValueAt(0, 4).toString();
        double peso = Double.parseDouble(tblUsuario.getValueAt(0, 5).toString());
        boolean amamentando = Boolean.parseBoolean(tblUsuario.getValueAt(0, 6).toString());
        boolean gestante = Boolean.parseBoolean(tblUsuario.getValueAt(0, 7).toString());
        int dian = Integer.parseInt(tblUsuario.getValueAt(0, 8).toString());
        int mesn = Integer.parseInt(tblUsuario.getValueAt(0, 9).toString());
        int anon = Integer.parseInt(tblUsuario.getValueAt(0, 10).toString());
        int quantidade = Integer.parseInt(tblUsuario.getValueAt(0, 11).toString());
        
        new MundoEducacao(id, nome, senha, idade, sexo, peso, amamentando, gestante, dian, mesn, anon, quantidade).setVisible(true);
        dispose();}
    catch(Exception a){
        JOptionPane.showMessageDialog(this, "Erro!");
    }
    }//GEN-LAST:event_btnMundoEducacaoActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        int id = Integer.parseInt(tblUsuario.getValueAt(0, 0).toString());
        String nome = tblUsuario.getValueAt(0, 1).toString();
        String senha = tblUsuario.getValueAt(0, 2).toString();
        int idade = Integer.parseInt(tblUsuario.getValueAt(0, 3).toString());
        String sexo = tblUsuario.getValueAt(0, 4).toString();
        double peso = Double.parseDouble(tblUsuario.getValueAt(0, 5).toString());
        boolean amamentando = Boolean.parseBoolean(tblUsuario.getValueAt(0, 6).toString());
        boolean gestante = Boolean.parseBoolean(tblUsuario.getValueAt(0, 7).toString());
        int dian = Integer.parseInt(tblUsuario.getValueAt(0, 8).toString());
        int mesn = Integer.parseInt(tblUsuario.getValueAt(0, 9).toString());
        int anon = Integer.parseInt(tblUsuario.getValueAt(0, 10).toString());
        int quantidade = Integer.parseInt(tblUsuario.getValueAt(0, 11).toString());
        
        new AtualizarDados(id, nome, senha, idade, sexo, peso, amamentando, gestante, dian, mesn, anon, quantidade).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        int id = Integer.parseInt(tblUsuario.getValueAt(0, 0).toString());
        String nome = tblUsuario.getValueAt(0, 1).toString();
        String senha = tblUsuario.getValueAt(0, 2).toString();
        int idade = Integer.parseInt(tblUsuario.getValueAt(0, 3).toString());
        String sexo = tblUsuario.getValueAt(0, 4).toString();
        double peso = Double.parseDouble(tblUsuario.getValueAt(0, 5).toString());
        boolean amamentando = Boolean.parseBoolean(tblUsuario.getValueAt(0, 6).toString());
        boolean gestante = Boolean.parseBoolean(tblUsuario.getValueAt(0, 7).toString());
        int dian = Integer.parseInt(tblUsuario.getValueAt(0, 8).toString());
        int mesn = Integer.parseInt(tblUsuario.getValueAt(0, 9).toString());
        int anon = Integer.parseInt(tblUsuario.getValueAt(0, 10).toString());
        int quantidade = Integer.parseInt(tblUsuario.getValueAt(0, 11).toString());
        
        new Historico(id, nome, senha, idade, sexo, peso, amamentando, gestante, dian, mesn, anon, quantidade).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHistoricoActionPerformed

    private void tblUsuarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblUsuarioPropertyChange
        tblUsuario.setVisible(true);
    }//GEN-LAST:event_tblUsuarioPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionarMetodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionarMetodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionarMetodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionarMetodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecionarMetodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCatracaLivre;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnMundoEducacao;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCCA;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblInformacaoCL;
    private javax.swing.JLabel lblInformacaoME;
    private javax.swing.JLabel lblSelecionarMetodo;
    private javax.swing.JLabel lblUsuario;
    private controle_de_consumo_de_agua.PainelImagemFundo painelImagemFundo1;
    private javax.swing.JTable tblUsuario;
    // End of variables declaration//GEN-END:variables
}
